import engarde.util.de_core as de_core
import unittest

data = {'delim_url': 'https://askfred.net/Results/roundResults.php?event_id=159843&seq=2&highlight_competitor_id=',
 'event_id': '159843',
 'rounds': [{'results': ['(1)Gregory, Aleksandra : ',
                         '(32)-Bye-',
                         '(17)McFadden, Emma : ',
                         '(16)Jogi, Raya : ',
                         '(9)Yerian, Ayda : ',
                         '(24)-Bye-',
                         '(25)-Bye-',
                         '(8)Han, Hannah : ',
                         '(5)Zhang, Victoria : ',
                         '(28)-Bye-',
                         '(21)-Bye-',
                         '(12)Geva, Eliana : ',
                         '(13)Barg, Daniella : ',
                         '(20)-Bye-',
                         '(29)-Bye-',
                         '(4)Senyuva, Su : ',
                         '(3)Barg, Margaret : ',
                         '(30)-Bye-',
                         '(19)Yilmaz, Pinar : ',
                         '(14)Yerian, Alayna : ',
                         '(11)Ahmed, Khadijah : ',
                         '(22)-Bye-',
                         '(27)-Bye-',
                         '(6)Nemeth, Katherine : ',
                         '(7)Kovalchuk, Erika : ',
                         '(26)-Bye-',
                         '(23)-Bye-',
                         '(10)Jogi, Shyla : ',
                         '(15)Shiv, Avni : ',
                         '(18)Tolsma, Chloe : ',
                         '(31)-Bye-',
                         '(2)Potapenko, Margarita : '],
             'round_no': 1},
            {'results': ['(1)Gregory, Aleksandra : ',
                         '(17)McFadden, Emma : ',
                         '10 - 5',
                         '(9)Yerian, Ayda : ',
                         '(8)Han, Hannah : ',
                         '(5)Zhang, Victoria : ',
                         '(12)Geva, Eliana : ',
                         '(13)Barg, Daniella : ',
                         '(4)Senyuva, Su : ',
                         '(3)Barg, Margaret : ',
                         '(19)Yilmaz, Pinar : ',
                         '10 - 6',
                         '(11)Ahmed, Khadijah : ',
                         '(6)Nemeth, Katherine : ',
                         '(7)Kovalchuk, Erika : ',
                         '(10)Jogi, Shyla : ',
                         '(15)Shiv, Avni : ',
                         '10 - 6',
                         '(2)Potapenko, Margarita : '],
             'round_no': 2},
            {'results': ['(1)Gregory, Aleksandra : ',
                         '10 - 0',
                         '(8)Han, Hannah : ',
                         '8 - 10',
                         '(5)Zhang, Victoria : ',
                         '10 - 3',
                         '(4)Senyuva, Su : ',
                         '9 - 10',
                         '(3)Barg, Margaret : ',
                         '10 - 2',
                         '(11)Ahmed, Khadijah : ',
                         '10 - 4',
                         '(10)Jogi, Shyla : ',
                         '4 - 10',
                         '(2)Potapenko, Margarita : ',
                         '3 - 10'],
             'round_no': 3},
            {'results': ['(1)Gregory, Aleksandra : ',
                         '10 - 1',
                         '(5)Zhang, Victoria : ',
                         '10 - 6',
                         '(3)Barg, Margaret : ',
                         '10 - 8',
                         '(2)Potapenko, Margarita : ',
                         '8 - 10'],
             'round_no': 4},
            {'results': ['(1)Gregory, Aleksandra : ',
                         '10 - 4',
                         '(2)Potapenko, Margarita : ',
                         '8 - 10'],
             'round_no': 5},
            {'results': ['(2)Potapenko, Margarita : ', '7 - 9'],
             'round_no': 6}],
 'tmt_id': '40216'}

res = [
 ('McFadden, Emma', 'Jogi, Raya', 10, 5),
 ('Yilmaz, Pinar', 'Yerian, Alayna', 10, 6),
 ('Shiv, Avni', 'Tolsma, Chloe', 10, 6),
 ('Gregory, Aleksandra', 'McFadden, Emma', 10, 0),
 ('Yerian, Ayda', 'Han, Hannah', 8, 10),
 ('Zhang, Victoria', 'Geva, Eliana', 10, 3),
 ('Barg, Daniella', 'Senyuva, Su', 9, 10),
 ('Barg, Margaret', 'Yilmaz, Pinar', 10, 2),
 ('Ahmed, Khadijah', 'Nemeth, Katherine', 10, 4),
 ('Kovalchuk, Erika', 'Jogi, Shyla', 4, 10),
 ('Shiv, Avni', 'Potapenko, Margarita', 3, 10),
 ('Gregory, Aleksandra', 'Han, Hannah', 10, 1),
 ('Zhang, Victoria', 'Senyuva, Su', 10, 6),
 ('Barg, Margaret', 'Ahmed, Khadijah', 10, 8),
 ('Jogi, Shyla', 'Potapenko, Margarita', 8, 10),
 ('Gregory, Aleksandra', 'Zhang, Victoria', 10, 4),
 ('Barg, Margaret', 'Potapenko, Margarita', 8, 10),
 ('Gregory, Aleksandra', 'Potapenko, Margarita', 7, 9)
]


class Test( unittest.TestCase ):
    def test_norm1(self):
        de = de_core.de2ser(de=data['rounds'])
        self.assertEqual( de, res)

if __name__ == '__main__':
    unittest.main()

'''
python engarde/test/unittest/util/test_core_de.py
'''