data = {
    'delim_url': 'https://askfred.net/Results/roundResults.php?event_id=146786&seq=2&highlight_competitor_id=',
    'event_id': '146786',
    'rounds': [
            {'results': ['(1)Patil, Aaryan : ',
                         '(16)Brubaker, Bronson : ',
                         '(9)Cook, Cole : ',
                         '(8)Tao, Jeffrey : ',
                         '(5)Sheres, Asher : ',
                         '(12)Wang, Kyle : ',
                         '(13)Arnold, Hali : ',
                         '(4)Chen, Lohen : ',
                         '(3)Qiu, Nathan : ',
                         '(14)Fu, Eunice : ',
                         '(11)Brum, Charles : ',
                         '(6)Wang, Sophia : ',
                         '(7)Okba, Noah : ',
                         '(10)Brown, Brandon : ',
                         '(15)Lo, Chloe : ',
                         '(2)Piec, Patrick : '],
             'round_no': 1},
            {'results': ['(1)Patil, Aaryan : ',
                         '10 - 4',
                         '(5)Sheres, Asher : ',
                         '10 - 5',
                         '(3)Qiu, Nathan : ',
                         '10 - 6',
                         '(2)Piec, Patrick : ',
                         '7 - 10'],
             'round_no': 3},
            {'results': ['(1)Patil, Aaryan : ',
                         '10 - 4',
                         '(3)Qiu, Nathan : ',
                         '10 - 2'],
             'round_no': 4},
            {'results': ['(3)Qiu, Nathan : ', '6 - 10'], 'round_no': 5}],
 'tmt_id': '37163'}
