data = {
     'date': '\nApr 29, 2018\n',
     'events': [
         {'event_id': '146786',
                 'event_name': ['\n',
                                'Y10 Mixed Saber:\n16 Competitors, a NR Event\n\n',
                                '\n'],
                 'fencers': [{'club': 'SPARTAK',
                              'fencer_id': '139652',
                              'fencer_name': 'Qiu, Nathan',
                              'place': '1',
                              'rating': 'U',
                              'rating_earned': ''},
                             {'club': 'LAGUNA',
                              'fencer_id': '143915',
                              'fencer_name': 'Patil, Aaryan',
                              'place': '2',
                              'rating': 'U',
                              'rating_earned': ''},
                             {'club': 'SPARTAK',
                              'fencer_id': '148916',
                              'fencer_name': 'Sheres, Asher',
                              'place': '3',
                              'rating': 'U',
                              'rating_earned': ''},
                             {'club': 'TTFC',
                              'fencer_id': '148285',
                              'fencer_name': 'Piec, Patrick',
                              'place': '3',
                              'rating': 'U',
                              'rating_earned': ''},
                            ],
                 },
                ],
     }